chore(systems): updates

diff --git a/assets/scripts/rebuild b/assets/scripts/rebuild
--- a/assets/scripts/rebuild
+++ b/assets/scripts/rebuild
@@ -3,7 +3,7 @@ Help()
 {
     echo "rebuild nixos-systems"
     echo
-    echo "syntax: rebuild [-h|a|u]"
+    echo "syntax: rebuild -[h|u|t|s|b|B|i]"
     echo "options:"
     echo "h     print this help"
     echo "u     update nix flake"
@@ -11,12 +11,13 @@ Help()
     echo "s     switch to new config"
     echo "b     only boot-entry for new config"
     echo "B     only build new config"
+    echo "i     interactive, only used for auto-update (run as root)"
     echo
 }
 COMMAND=""
 OPTIONS=""
 
-while getopts ":hutsbB" option; do
+while getopts ":hutsbBi" option; do
     case $option in
         h)
             Help
@@ -31,19 +32,52 @@ while getopts ":hutsbB" option; do
             COMMAND_OVERRIDE="boot" ;;
         B)
             COMMAND_OVERRIDE="build" ;;
+        i)
+            interactive=true ;;
         \?)
             echo "Error: invalid option"
             exit ;;
     esac
 done
 
-pushd "$DOTFILES_PATH" || exit
+DATE=$(date)
+hostname=$(hostname)
+
+echo "[$DATE] Starting NixOS update"
+
+if [[ "$interactive" == true ]]; then
+    USER="armin"
+    BUS_ADDRESS="unix:path=/run/user/1000/bus" # ???
+
+    cd "/home/armin/dotfiles" || { echo "[$DATE] Failed to cd into dotfiles directory"; exit 1; }
+    if ! sudo -u armin git add --all; then
+        echo "[$DATE] Failed to run 'git add'"
+        exit 1
+    fi
+
+    if ! sudo -u armin nix flake update; then
+        echo "[$DATE] Failed to run 'nix flake update'"
+        exit 1
+    fi
+
+    if ! /run/current-system/sw/bin/nixos-rebuild boot --flake "/home/armin/dotfiles?submodules=1#$hostname" &> /tmp/auto-update.log ; then
+        echo "[$DATE] nixos-rebuild failed"
+        sudo -u armin DBUS_SESSION_BUS_ADDRESS="$BUS_ADDRESS" DISPLAY=:0 \
+            notify-send -e 'NixOS' '[auto-update] failure: check /tmp/auto-update.log for more info' --icon=/home/armin/dotfiles/assets/pics/NixOS.png -u critical
+        exit 1
+    fi
+    echo "[$DATE] NixOS update completed successfully"
+    sudo -u armin DBUS_SESSION_BUS_ADDRESS="$BUS_ADDRESS" DISPLAY=:0 \
+        notify-send -e 'NixOS' '[auto-update] success' --icon=/home/armin/dotfiles/assets/pics/NixOS.png
+    exit 0
+fi
+
+pushd "$DOTFILES_PATH" || { echo "[$DATE] Failed to cd into dotfiles directory"; exit 1; }
 git pull
 git submodule update --recursive
 
 nixfmt .
 echo "NixOS Rebuilding..."
-hostname=$(hostname)
 
 git add --all # add all files for the rebuild
 
